spring:
  application:
     name: user-server
  profiles:
     active: userDevA
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    # 指定注册中心的地址
  instance:
     preferIpAddress: true