spring:
  profiles:
    active: eurekaDevA
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0